# ===============================
# DATABASE CONNECTION
# ===============================

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: Bdd13Mdp00!

# ===============================
# JPA / HIBERNATE
# ===============================

  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect